Write a Python Program to Add Two Matrices?

In [1]:
#solution 1
mat1 = [[1,6,4],
        [4,5,6],
        [7,6,9]]

mat2 = [[2,5,4],
        [5,8,7],
        [8,3,1]]

sumMat = [[0,0,0],
          [0,0,0],
          [0,0,0]]

sumMat = [[mat1[i][j] + mat2[i][j] for j in range(len(mat1[0]))] for i in range(len(mat1))]
print("The Sum of two matrix {}  and {}  is \n{} ".format(mat1,mat2,sumMat))

The Sum of two matrix [[1, 6, 4], [4, 5, 6], [7, 6, 9]]  and [[2, 5, 4], [5, 8, 7], [8, 3, 1]]  is 
[[3, 11, 8], [9, 13, 13], [15, 9, 10]] 


In [3]:
# solution 2
import numpy as np

mat1 = np.array([[1,6,4],
        [4,5,6],
        [7,6,9]])
mat2 = np.array([[2,5,4],
        [5,8,7],
        [8,3,1]])

sumMat = np.add(mat1,mat2)
print("The Sum of two matrix \n\n{}  and \n\n{}  is \n\n{} ".format(mat1,mat2,sumMat))

The Sum of two matrix 

[[1 6 4]
 [4 5 6]
 [7 6 9]]  and 

[[2 5 4]
 [5 8 7]
 [8 3 1]]  is 

[[ 3 11  8]
 [ 9 13 13]
 [15  9 10]] 


Write a Python Program to Multiply Two Matrices?

In [13]:
#solution 1
mat1 = [[1,6,4],
        [4,5,6],
        [7,6,9]]

mat2 = [[2,5,4],
        [5,8,7],
        [8,3,1]]

result = [[0,0,0],
          [0,0,0],
          [0,0,0]]

for i in range(len(mat1)):
 
    # iterating by column by B
    for j in range(len(mat2[0])):
 
        # iterating by rows of B
        for k in range(len(mat2)):
            result[i][j] += mat1[i][k] * mat2[k][j]
 

print(f"Product of \n\n{mat1} and \n\n{mat2} is \n\n{result}")

Product of 

[[1, 6, 4], [4, 5, 6], [7, 6, 9]] and 

[[2, 5, 4], [5, 8, 7], [8, 3, 1]] is 

[[64, 65, 50], [81, 78, 57], [116, 110, 79]]


In [5]:
# solution 2
import numpy as np

mat1 = np.array([[1,6,4],
        [4,5,6],
        [7,6,9]])
mat2 = np.array([[2,5,4],
        [5,8,7],
        [8,3,1]])

sumMat = np.dot(mat1,mat2)
print("The product of two matrix \n\n{}  and \n\n{}  is \n\n{} ".format(mat1,mat2,sumMat))

The product of two matrix 

[[1 6 4]
 [4 5 6]
 [7 6 9]]  and 

[[2 5 4]
 [5 8 7]
 [8 3 1]]  is 

[[ 64  65  50]
 [ 81  78  57]
 [116 110  79]] 


Write a Python Program to Transpose a Matrix?

In [14]:
matrix = [[1, 1, 1, 1],
          [2, 2, 2, 2],
          [3, 3, 3, 3],
          [4, 4, 4, 4]]
 
transpose = [list(row) for row in zip(*matrix)]
 
print("Original Matrix:")
for row in matrix:
    print(row)
 
print("Transposed Matrix:")
for row in transpose:
    print(row)

Original Matrix:
[1, 1, 1, 1]
[2, 2, 2, 2]
[3, 3, 3, 3]
[4, 4, 4, 4]
Transposed Matrix:
[1, 2, 3, 4]
[1, 2, 3, 4]
[1, 2, 3, 4]
[1, 2, 3, 4]


Write a Python Program to Sort Words in Alphabetic Order?

In [16]:
def sort_strng(strng:str):
    """sort list in alphabatical order"""
    lst=[i for i in strng]
    lst.sort()
    return "".join(lst)


In [17]:
sort_strng("curve")

'ceruv'

Write a Python Program to Remove Punctuation From a String?

In [18]:
def no_punc(strng:str):
    """remove punctuation from string"""
    punc=punctuations = '''!()-[]{};:'"\,<>./?@#$%^&*_~'''
    lst=[]
    for i in strng:
        if i not in punc:
            lst.append(i)
    return "".join(lst)


In [19]:
no_punc("bad! bom$$$b")

'bad bomb'